// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var PathRebuild = require("../PathRebuild.bs.js");

describe("parse", (function () {
        test("example", (function () {
                expect(PathRebuild.parse("{0..-3}/{-2}.js")).toEqual({
                      TAG: /* Ok */0,
                      _0: [
                        {
                          TAG: /* Range */0,
                          _0: 0,
                          _1: -3
                        },
                        /* Sep */0,
                        {
                          TAG: /* Range */0,
                          _0: -2,
                          _1: -2
                        },
                        {
                          TAG: /* Literal */1,
                          _0: ".js"
                        }
                      ]
                    });
                
              }));
        
      }));

describe("print", (function () {
        test("example", (function () {
                var parsed = PathRebuild.parseExn("{0..-3}/{-2}.js");
                expect(PathRebuild.print("/", parsed, "file.sql")).toEqual({
                      TAG: /* Ok */0,
                      _0: "file.js"
                    });
                
              }));
        
      }));

/*  Not a pure module */
