// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function each(data, title, f) {
  return test.each(data)(title + " (%#) %p", f);
}

function each2(data, title, f) {
  return test.each(data)(title + " (%#) %p %p", f);
}

exports.each = each;
exports.each2 = each2;
/* No side effect */
